---
version: 2.1

jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    steps:
    - checkout
    - run: sudo apt-get -y install file
    - run: mkdir -v build
    - run: go get github.com/mattn/go-sqlite3
    - run: make -C stuff -f Makefile stuff
    - run: make -C stuff -f Makefile test
    - run: mv stuff/stuff build/stuff
    - run: file build/*
    - persist_to_workspace:
        root: .
        paths:
        - build
    - store_artifacts:
        path: build

workflows:
  version: 2
  stuff:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
