---
version: 2.1

jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    steps:
    - checkout
    - run: sudo apt-get -y install file
    - run: go mod download
    - run: mkdir -v build
    - run: make -C stuff style
    - run: make -C stuff stuff
    - run: make -C stuff test
    - run: mv -v stuff/stuff build/stuff-amd64
    - run: GOARCH=arm GOARM=5 make -C stuff stuff
    - run: mv -v stuff/stuff build/stuff-armv5
    - run: file build/*
    - persist_to_workspace:
        root: .
        paths:
        - build
    - store_artifacts:
        path: build

  release:
    docker:
    - image: circleci/golang:1.11

    steps:
    - checkout
    - run: sudo apt-get update
    - run: sudo apt-get -y install fakeroot
    - run: mkdir -v -p ${HOME}/bin
    - run: curl -L 'https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2' | tar xvjf - --strip-components 3 -C ${HOME}/bin
    - attach_workspace:
        at: .
    - run: mkdir "stuff-org-${CIRCLE_TAG}"
    - run: cp -r stuff/static "stuff-org-${CIRCLE_TAG}/static"
    - run: cp -r stuff/template "stuff-org-${CIRCLE_TAG}/template"
    - run: cp build/stuff-amd64 "stuff-org-${CIRCLE_TAG}/stuff-org"
    - run: fakeroot tar -czvf ../stuff-org-${CIRCLE_TAG}.amd64.tar.gz "stuff-org-${CIRCLE_TAG}"
    - run: cp build/stuff-armv5 "stuff-org-${CIRCLE_TAG}/stuff-org"
    - run: fakeroot tar -czvf ../stuff-org-${CIRCLE_TAG}.armv5.tar.gz "stuff-org-${CIRCLE_TAG}"
    - run: sha256sum stuff-org-*.tar.gz | tee sha256sums.txt
    - run: >
        for file in stuff-org-*.tar.gz sha256sums.txt ; do
          ${HOME}/bin/github-release upload \
            --user "${CIRCLE_PROJECT_USERNAME}" \
            --repo "${CIRCLE_PROJECT_REPONAME}" \
            --tag "${CIRCLE_TAG}" \
            --name "${file}" \
            --file "${file}"
        done

workflows:
  version: 2
  stuff:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
